#!/bin/sh

RDIO_SERVER=http://localhost:8083

init(){
  PLAYBACK_TOKEN="GAlNi78J_____zlyYWs5ZG02N2pkaHlhcWsyOWJtYjkyN2xvY2FsaG9zdEbwl7EHvbylWSWFWYMZwfc="
  curl --data-urlencode "playbackToken=$PLAYBACK_TOKEN" $RDIO_SERVER/init
}

# play the first track result of a search
play(){
  KEY=$(search "$1" | sed -n 1p | cut -d' ' -f2)
  curl --data "key=$KEY" $RDIO_SERVER/play
}

pause(){
  curl $RDIO_SERVER/pause
}

stop(){
  curl $RDIO_SERVER/stop
}

search(){
  ruby search.rb "$1" | tee results.txt
}

#next(){ curl $RDIO_SERVER/next }
#previous(){ curl $RDIO_SERVER/previous }
#seek(){ curl $RDIO_SERVER/seek }
#setShuffle(){ curl $RDIO_SERVER/setShuffle }
#setRepeat(){ curl $RDIO_SERVER/setRepeat }
#queue(){ curl $RDIO_SERVER/queue }
#setVolume(){ curl $RDIO_SERVER/setVolume }
#setMute(){ curl $RDIO_SERVER/setMute }
#playQueuedTrack(){ curl $RDIO_SERVER/playQueuedTrack }
#moveQueuedSource(){ curl $RDIO_SERVER/moveQueuedSource }
#clearQueue(){ curl $RDIO_SERVER/clearQueue }
#setCurrentPosition(){ curl $RDIO_SERVER/setCurrentPosition }
#removeFromQueue(){ curl $RDIO_SERVER/removeFromQueue }
#sendState(){ curl $RDIO_SERVER/sendState }
#startFrequencyAnalyzer(){ curl $RDIO_SERVER/startFrequencyAnalyzer }
#stopFrequencyAnalyzer(){ curl $RDIO_SERVER/stopFrequencyAnalyzer }
