#!/bin/bash

URL=http://localhost:5000

play() {
  curl $URL/play --data "key=$1&initialPosition=$2"
}

pause() {
  curl $URL/pause
}

stop() {
  curl $URL/stop
}

next() {
  curl $URL/next
}

previous() {
  curl $URL/previous
}

seek() {
  curl $URL/seek --data "position=$1"
}

setShuffle() {
  curl $URL/setShuffle --data "shuffle=$1"
}

setRepeat() {
  case $1 in
    0|"no-repeat") mode=0
      ;;
    1|"track-repeat") mode=1
      ;;
    2|"whole-source-repeat") mode=2
      ;;
    *) echo "Usage: $0 setRepeat no-repeat|track-repeat|whole-source-repeat"
      exit 2
  esac
  curl $URL/setRepeat --data "mode=$mode"
}

queue() {
  curl $URL/queue --data "key=$1"
}

setVolume() {
  curl $URL/setVolume --data "volume=$1"
}

setMute() {
  curl $URL/setMute --data "mute=$1"
}

playQueuedTrack() {
  curl $URL/playQueuedTrack --data "position=$1&offset=$2"
}

moveQueuedSource() {
  curl $URL/moveQueuedSource --data "from=$1&to=$2"
}

clearQueue() {
  curl $URL/clearQueue
}

setCurrentPosition() {
  curl $URL/setCurrentPosition --data "sourceIndex=$1"
}

removeFromQueue() {
  curl $URL/removeFromQueue --data "sourceIndex=$1"
}

sendState() {
  curl $URL/sendState
}

startFrequencyAnalyzer() {
  curl $URL/startFrequencyAnalyzer --data "period=$1&frequencies=$2"
}

stopFrequencyAnalyzer() {
  curl $URL/stopFrequencyAnalyzer
}

search() {
  curl $URL/search --data "query=$1"
}

case $1 in
  play) play $2
    ;;
  pause) pause
    ;;
  stop) stop
    ;;
  next) next $2
    ;;
  previous) previous
    ;;
  seek) seek $2
    ;;
  setShuffle) setShuffle $2
    ;;
  setRepeat) setRepeat $2
    ;;
  queue) queue $2
    ;;
  setVolume) setVolume $2
    ;;
  setMute) setMute $2
    ;;
  playQueuedTrack) playQueuedTrack $2 $3
    ;;
  moveQueuedSource) moveQueuedSource $2 $3
    ;;
  clearQueue) clearQueue
    ;;
  setCurrentPosition) setCurrentPosition $2
    ;;
  removeFromQueue) removeFromQueue $2
    ;;
  sendState) sendState
    ;;
  startFrequencyAnalyzer) startFrequencyAnalyzer $2 $3
    ;;
  stopFrequencyAnalyzer) stopFrequencyAnalyzer
    ;;
  search) search "$2"
    ;;
  *) echo "Usage: $0 play|pause|stop|next|previous|seek|setShuffle|setRepeat|queue|setVolume|setMute|playQueuedTrack|moveQueuedSource|clearQueue|setCurrentPosition|removeFromQueue|sendState|startFrequencyAnalyzer|stopFrequencyAnalyzer|search"
    exit 1
esac
